config/routes.rb
Rails.application.routes.draw do
  root 'messages#index'
  resources :messages , except: [:index, :new]
end

app/models/message.rb
class Message < ActiveRecord::Base
  # 名前は必須入力かつ20文字以内
  validates :name , length: { maximum: 20 } , presence: true
  # 内容は必須入力かつ2文字以上30文字以下
  validates :body , length: { minimum: 2, maximum: 30 } , presence: true
  
  validates :age , numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :age , numericality: { :less_than => 200 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
  def logged_in_user
    unless logged_in?
      store_location
      flash[:danger] = "Please log in."
      redirect_to login_url
    end
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_message, only: [:edit, :update, :destroy]


def destroy
    @message.destroy
    redirect_to root_path, notice: 'メッセージを削除しました'
  end

 def index
    @message = Message.new
    # Messageを全て取得する。
    @messages = Message.all
end
  def create
    @message = Message.new(message_params)
    if @message.save
      redirect_to root_path , notice: 'メッセージを保存しました'
    else
      # メッセージが保存できなかった時
      @messages = Message.all
      flash.now[:alert] = "メッセージの保存に失敗しました。"
      render 'index'
    end
  end
  
   def edit
  end
  
  def update
    if @message.update(message_params)
      # 保存に成功した場合はトップページへリダイレクト
      redirect_to root_path , notice: 'メッセージを編集しました'
    else
      # 保存に失敗した場合は編集画面へ戻す
      render 'edit'
    end
  end
  
  def set_message
    @message = Message.find(params[:id])
  end
end

  
  private
  def message_params
    params.require(:message).permit(:name, :age, :body,)
  end
  ## ここまで

 

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      flash[:info] = "logged in as #{@user.name}"
      redirect_to @user
    else
      flash[:danger] = 'invalid email/password combination'
      render 'new'
    end
  end
  
  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end

  def store_location
    session[:forwarding_url] = request.url if request.get?
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>チャット式交流場</title>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.4/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "cha", :media => "all" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <nav class="navbar">
    <div class="container">
      <div class="navbar-header">
        <a class="navbar-brand" href="#"><h1>チャット式交流</h1></a>
      </div>
    </div>
  </nav>
  <div class="container">
  <% if notice %>

      <div class="alert alert-info">
        
<%= notice %>

      </div>
    
<% end %>

    
    
<%= yield %>

  </div>
</body>
</html>

app/views/messages/_form.html.erb
<div class="col-sm-6">
  <%= form_for(@message, html: {class: "form-horizontal"}) do |f| %>
    <% if @message.errors.present? %>
      <div class="alert alert-danger">
        <%= alert %>
        <ul>
          <% @message.errors.full_messages.each do |full_message| %>
            <li><%= full_message %></li>
          <% end %>
        </ul>
      </div>  
    <% end %>

    <h3>メッセージを書き込む</h3><br>

    <div class="form-group">
      <label for="message_name" class="control-label col-md-2">名前:</label>
      <div class="col-md-10">
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <label for="message_age" class="control-label col-md-2">年齢:</label>
      <div class="col-md-10">
        <%= f.text_field :age, class: "form-control" %>
      </div>
    </div>

    <div class="form-group">    
      <label for="message_body" class="control-label col-md-2">内容:</label>
      <div class="col-md-10">
        <%= f.text_area :body, class: "form-control" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
        <%= f.submit "書き込む", :class => "btn btn-success btn-lg" %>
      </div>
    </div>
  <% end %>
</div>

app/views/messages/edit.html.erb
<h1>メッセージの編集</h1>

<%= render 'form' %>

app/views/messages/index.html.erb
<div class="row">
  <div class="col-sm-6 .hidden-xs">
    <div class="panel-heading">
      <h3>メッセージ一覧</h3>
      <div class="panel-body">
        <% @messages.each do |message| %>
          <p class="who"><%= message.name %> <%= message.age %>歳</p>
          <p class="who2"><%= message.body %></p>
            (<%= link_to "edit" , edit_message_path(message) %>
         <%= link_to "destroy" , message , method: :delete, data: { confirm: '削除してもよろしいですか？' } %>)
        <% end %>
      </div>
    </div>
  </div>

  <%= render 'form' %>
</div>